import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import Script from "next/script";
import { TelegramProvider } from "@/lib/TelegramProvider";
import { CartProvider } from "@/lib/CartProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <TelegramProvider>
            <CartProvider>
                <html lang="en" suppressHydrationWarning>
                    <body
                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                        suppressHydrationWarning
                    >
                        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
                        <div>
                            <Header />
                            <main className="flex-1 min-h-screen">{children}</main>
                            <Footer />
                        </div>
                    </body>
                </html>
            </CartProvider>
        </TelegramProvider>
    );
}
